---
- name: Postfixのインストール作業(Ubuntu)
  hosts: all
  gather_facts: yes
  tasks:
    - name: パッケージリストを更新してPostfixをインストール
      ansible.builtin.apt:
        name: postfix
        state: present
        update_cache: yes
