---
- name: Nginxコンテナの自動構築
  hosts: all
  become: yes
  tasks:
    - name: Docker SDK for Pythonの準備 (直接コマンドで実行)
      command: dnf install -y python39-pip
      changed_when: false

    - name: Docker SDK for Pythonをインストール (Python3.9用)
      pip:
        name: docker
        executable: pip3.9
        state: present

    - name: HTTP(80番)ポートを開放する (直接コマンドで実行)
      command: firewall-cmd --add-port=80/tcp --permanent
      changed_when: false

    - name: ファイアウォールの設定を反映
      command: firewall-cmd --reload
      changed_when: false

    - name: Nginxコンテナを起動する
      community.docker.docker_container:
        name: my-nginx
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
